name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  golangci:
    strategy:
      matrix:
        go-version: ^1.13
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: run lint
        run: make lint
